Added better functionality to file selector input, fixed some bugs, m…
leomariga/gpt-engineer pull request #1
Opened 2023-07-11 07:26 UTC by lectair

…isspellings and cleaned up. Added prompts to make sure code generation goes right.

2023-07-12 02:02 UTC, leomariga commented
Thanks! @lectair I'll have a look at this PR asap.

2023-07-12 02:33 UTC, leomariga requested changes
@lectair Thanks for helping with this PR =)  I liked very much the implementation of "all" files and fixing the camel case vars. I didn't have time to test it yet, but I'll do it tomorrow.

There are other files that were committed which I think was by mistake. I also put some considerations on changes that I think are out of the context of this PR and maybe should be done in a different PR in the official repository, like the changes in the prompts. 

Would you mind doing it? I'll merge your solution on my repo so we can merge in gpt-engineer.

2023-07-12 02:33 UTC, leomariga commented on gpt_engineer/.gpteng/file_list.txt
I think this should not be committed right? =)

2023-07-12 02:33 UTC, leomariga commented on gpt_engineer/preprompts/generate
I think this file is out of context with the current implementation of our PR "Improve existing files". Maybe it would be better to create another PR in gpt-engineer official repo with this change.

2023-07-12 02:33 UTC, leomariga commented on gpt_engineer/preprompts/philosophy
I think this is also out of the context of the PR. Don't you think? I would like to keep this PR limited to the scope of fixing existing files not change the other steps if possible. But you could open another PR in the official repository. =)

2023-07-12 02:33 UTC, leomariga commented on gpt_engineer/preprompts/respec
Same os others.

2023-07-12 02:33 UTC, leomariga commented on gpt_engineer/preprompts/use_feedback
What happened here? =)

2023-07-12 02:33 UTC, leomariga commented on requirements.txt
I did not understand why do we need to change the requirements in this PR.

2023-07-19 18:00 UTC, lectair reviewed
Hello @leomariga. Sorry for not replying sooner, I've been the last week quite busy.

Yes, you are absolutely right about the irrelevant changes. It's the first PR I do, sorry. Ignore all the preprompts and requirements. I simply changed everything I saw necessary without splitting it into different PRs. I know my way around GitHub more or less but I'm still learning how to collaborate on other people's repositories. 

I have fixed the problems you told me about. Thank you very much for your suggestions, for taking the time to respond and your patience.

2023-07-19 18:36 UTC, lectair commented on requirements.txt
Removed file

2023-07-19 18:37 UTC, lectair commented on gpt_engineer/preprompts/use_feedback
Just an error.

2023-07-19 18:37 UTC, lectair commented on gpt_engineer/.gpteng/file_list.txt
You're right, removed.

2023-07-21 02:00 UTC, leomariga approved these changes
Nice!

2023-07-21 02:05 UTC, merged